services:
  db:
    image: postgres:15
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - .env.test
    ports:
      - "5454:5432"
    networks:
      - chanx

  redis:
    image: redis:7
    ports:
      - "6363:6379"
    networks:
      - chanx

volumes:
  dbdata:

networks:
  chanx:
    driver: bridge
