import json
from pathlib import Path

from fastapi.testclient import TestClient

from sandbox_fastapi.main import app

client = TestClient(app)

results_dir = Path(__file__).parent / "test_results"


def test_asyncapi_schema_html_doc() -> None:
    response = client.get("/asyncapi")
    assert response.status_code == 200
    assert "AsyncApiStandalone.render" in response.text
    assert "Websocket API documentation generated by Chanx" in response.text


def test_asyncapi_schema_json() -> None:
    response = client.get("/asyncapi.json")
    assert response.status_code == 200
    data = response.json()

    with open(results_dir / "asyncapi_schema_res.json", "w") as f:
        json.dump(data, f, indent=2)

    with open(results_dir / "asyncapi_schema.json") as f:
        expected_data = json.load(f)

    assert data == expected_data


def test_asyncapi_schema_yaml() -> None:
    response = client.get("/asyncapi.yaml")
    assert response.status_code == 200
    data = response.text

    with open(results_dir / "asyncapi_schema_res.yaml", "w") as f:
        f.write(data)

    with open(results_dir / "asyncapi_schema.yaml") as f:
        expected_data = f.read()

    assert data == expected_data
